language: node_js

env:
  global:
    - CXX=g++-4.8
    # DEV_AWS_ACCESS_KEY
    - secure: "kBF8LDGFRgHzSewq3ZDuEt8Uojcsnd+CPD4tvcUvtEYZ0xIg0cBdFr2CcO6RzAOmFasJDqbkWv4nJBTphS7zdkiPeEwzFs8X+BYc1z+eTW8hXMSNkCN2bTJK36jORWMw45dDvSUhS854/ELrRSQFaquBH4hzkBywlgSrpvRkxgVAuXEmJzsvfl2uUNnWiff1hC4hlOK1SA5K0jzBNICU1HOcvaQ/Az11ec/NhcahKJaOaYT8NNYIhceW6uVsDfjsCcQxVjMg2TbCQBZDK2+fXbGyEMgDzPTqdgHM6jJwJT29gvL9QaIO5YRaWy9DwEwijNGCaF2dnEIYPmgpMPzvH+834zqVy1x3rDVB4aSxxe3C6u4Afjv5VXAQFHz0wwyO8LY4BMZx++R49tmVrUhDaxCCCfy4nreV+8KLlbQAfgLwhIccAtkyMAO4fRpBeUwHZZ2Nr8G1+x8bz/dXQ8ZfCYMLqsmp5Oi48RMR92h3zU2HpZe+2a5TDwBlemupXLEPynCn+dNTGWaqldBRv7u+R0XgG22V6thXh3UGKDXGKqFlUldNHurXc0rJvEFWTPKhdFZJ3ryoZF59YLmaRt5mpO9LhQOLyA9COvieYzwph57Plmel2KCRpccE4t+Rp7r1P0M+DAyvfmILHXqekT+KJsVygm+SnocsZ1BYzha8NSI="
    # DEV_AWS_SECRET_KEY
    - secure: "oR2OSmh1bOrxkQrtX7a4MarN29rblCZq3qnQN93+2eWCqYbBiy+h5uC/fJFzoVOGGZDxYaln3ezjLDkwQ0uUPoo1eU+SSRLRGaV/3+M2Hr5F7bsOviUGSfDmwZRf8pF0bQufPDkQgaifJZqHKbz9agQALw/H0G3eqqvMRpurfu+1I54jTPSlsHqV1+u6QncSr6y4ywoLVKiv0CXeFJuXzETJ0GRW4xPGjdy+AEOvSL/dL7EjQhRG1o2BQ8XKICYxe15RGfDA0ItGlUgZn82F5f+AhGxGbiPpjXlx2gWQpow3Fbs+n4cgVZNF0bCQE6FR5hn2xJl2bDv6pJUQwJY2kX99lThl63aFjH/64CBs/qsCW5ijGaV5VDy1mQuMg4nsb/qt8IYNRt9ieydrdSDHAxzRPFLl01oDdzCQplq/ICeet212iC1B2j26LvZR6plzTpWxt7l3lzJTsEAzPQBnh+vkBHvmM/fQz+u3URVEkayfPPSd4817oCChUZiBgna7KjdQn1FSJh5COSDSDCwDidhXxHpyNuOqlhO/xs5VYshFjTu7kIEv8fGifTKdq6zh9YRGi382UUn+Oc8LXqr+wOJwtVEu2dlqkCUcEhzyAiCb3SBc3S4GA1APD3Cl4q2EDL7WQ8/LMR/DkAbCATneYi2m+Vlcyg71nhwFwSP0+xw="
    # STAGING_AWS_ACCESS_KEY
    - secure: "TR2ATVGhGdyvRhuSW68mphnL0+Lwshps9WnVN/pprefEjvxUdabI2NBjOBZdnh3n/cqVy2wOnLlxMDKJY/2HnaAda649NHlZpUB8/d1yEAXUv/xEXxc7YQVJESGzm2ugHMrioVBXjzHn2iPB4P6NB5SWUE9+oYRGUTMi298aZgQAVBgszvaXkleeks/rac3Y/BWicZg4gGTnVJHE0ASUGbEMBs4QwMS2/g5g5lDCuY768P6qKVym+rlGf/8JqetQZ/qD0KE2IGLl5NHCzgyFUrNOQyQ+o/m/PDlocMGnHkInL6PEiA1G8rEcwrPUUP0KpIcKc5YJtGZoFt5g09zk64XitcnwsjQEzEIlUuePFWjKdSrhKIOsIc89trAimoZo8q945fsD78iCVa6WR4+4rvuR2Ycn1428QLQsQe+1C3jnmvfa1OG05oq91hiQzvw0IGnjfNsWK7kg4rDjSZ5pZehO0FZh30ihYor2f1kPJR1FryChD9WoLuMlLmBiCs+cMAHTq5Z6uH8UIuSBZQiyoqZ67qBJq8PspGyULJn1MAtv8KuPho9K6Sdr5y2FOlmIgtnXDOX/eVwBn7WLnGnUzGJsgshaC120a7bcenczL0rLLzSUxUZBWFy2M6ZfpnHE4vStqYlIqWlC40onZvi5YihhrctMlo5OZKLQ5bvI+U8="
    # STAGING_AWS_SECRET_KEY
    - secure: "NshonUay7bQITS59Jbao5s3ePFSQbqVmiQ6Qj3AlSt10bu2aXLhHdiOKvi3k6q+0kCIBZb8M9qE6tAfDmmsm2G1FyCAro/UFTIA8Wo3v5DRnNN36nz/8d3E5PrlJiT/vJbKjfEB79jxIqpNQsz8lfVvrLnaSljWXiZl16VpjB4nV+4YRKBJ2la+X3LD9JmRzBVbXZPgYlitfsyEunEFhOhwX0sjxclybMr9PmePvUeAX3+WsdIxFIyomQxDGghPWbdd8E+egnX82DZvQdaS3SI1hI8DTxyQjWg98/UpDwnqKUCJttwZpBcyTNQlHOcDA7ea2lDpIPwaWgDScgarktjsr8qyGeFC6AlddQL014OY7bFGwdcHrgSz9oJ3eaSYv1rzacgpkK/AeuQgKDhSeEigTK6aeoCJdbe4ElKRxYJOsL3kmTWRx5QLH3Fu84BxiwhCO2N65cA1ioqZuUFuUAW+NwycOJV8Q+CGd//xbDw5UvKw1QYm2VqFSJ0xiHZK2Noiz2rC2FoNUjfttmJMYLPMoC57HzcPkBgDCbrGXhDWrOuf8EdNZvN2YBUde3WkgUn/Xf7XwE+IV4lcBtVBrVeqITYg0UKNnMx4JKCt7L7v+Xl2pvUlbXd0ItxW1d0DSt8P+x3ierOeD6KIdZWK+G4Rm1d8/zQzYxXI0UZiX97Q="

notifications:
  email: false

before_install:
  - npm install -g npm@3.8.9
  - npm --version

cache:
  apt: true
  directories:
  - node_modules

script:
  - npm run lint
  - npm run build
  - npm run selenium:bootstrap
  - npm run test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_deploy:
  - npm install -g s3-cli

deploy:
  - provider: script
    script: AWS_ACCESS_KEY=${DEV_AWS_ACCESS_KEY} AWS_SECRET_KEY=${DEV_AWS_SECRET_KEY} s3-cli sync --acl-public --delete-removed --recursive --region us-gov-west-1 build/development s3://dev.vets.gov/
    skip_cleanup: true
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: burn-the-world
  - provider: script
    script: AWS_ACCESS_KEY=${STAGING_AWS_ACCESS_KEY} AWS_SECRET_KEY=${STAGING_AWS_SECRET_KEY} s3-cli sync --acl-public --delete-removed --recursive --region us-gov-west-1 build/staging s3://dev.vets.gov/
    skip_cleanup: true
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: master
  - provider: s3
    access_key_id: AKIAKO2IAN6AOQEYC2HQ # awong govcloud key.
    secret_access_key:
      secure: vsDSvLeP0CWLEAbffadOH04hriQDw/GdvuKt5me77v7SjAAzZZNb8IPai6leOebgn/Sr/NvsKXUFrMzvLUAjwmH91VDEnq/YsPWzqqlDpONTVbBkiJQDKS+plVNLQZXQ89+6WVKcAOdFLmUH5EwxUpliEGrzdCcxY6v59DiETOykhsouLwDxirBGzgfBqZ46ARiFl2xRS8HYmlavcm8SP4CQFLlFTmFVYMji3waGRk4xaXv+E50iHI2J1Hjo48C7XW/x9oITTZiZnxNLql59lzczDyvdyYBdK/nNQReBatDxUElATQ7s2CfPGDHMaRcJ+6LxxJBXo3hlhD6cDC6ao9q8SqOc1DK5aSfUkt4G97eHeKUMro+BE5+ZkJ6xAszLT19Az6CefT+pEySbLl3RYeUBRvXn+6L5kPlEcSzCX5MXuOpEvQaxAxtsD083Q5Xv6dSa0e63WxlzfqirBDqaFvOtguYnNkS/g0kYGCQBfdkdLAuR45ylE8ElBod8izmdkqGQPu2JtHuisN3VolJQS+sx8KMbwaeHRZCDPpyLjJ9EHUnnEplH+mawKqDi3zkL3PprFH5Tj3f4cVLqR62IoqTbZA8ihOLDDSjuZs9G8Txe19Ehsks0VSzgdgR12CYpW8dGa99ULxUlmYUaBZfVrxmve19vLeYtY+Xwk0+gaPg=
    bucket: dev.vets.gov
    skip_cleanup: true
    region: us-east-1
    local-dir: build
    acl: public_read
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: burn-the-worlda
  - provider: s3
    access_key_id: AKIAIEIFFI3LJZO44VTQ
    secret_access_key:
      secure: PKZPLle45zyvca1I3w8gxkwznCWM/EUqfw7W8WOGmHBDqvnZ24Cc26pOSKDE8p250rnDX42cxrnOuuGJUNpVTWoIdtKrfi3YEZi8yBXwMecKHsaZO3jQrWtGFVHV747gDmjx7THsacgAn5mvgZkuHXOZXpWcJaQtOLjLhqx++tuKSuSOkFENlRjm5fZWGUkWCBR4HjJPdfFazl8sE7TDomuOEumCjtqeKNFumlrPs+H34OyMpiMidU24Nsbla0exV7YkJTJ2PrdtkYFB3p6zZP26CHv12odkCsauZ3Ee1MUcmolNb3VgK6RPGiBvcozP7u/SdbXb5JYwBT/x/ffkowCcIZ+PNSzh/QF/TdJ0c2vtkfhTCiBDiOnBosFf3DAFCtXRCLEIlJtlxDbavBLTIEMnwkNKAQIRZP5ro4zMGjAJP/AWE0YvYZCQO8YXlb/Pl8QsH8HZY2+EYR8Qrjg/NcnnDfkg9rGdyslY/e9oMoJYYgmJlwpuIMlAWylhqUHfCzGFtUzTV+8GARjM7kkMwtIUqsjBbEYNu+kzd7O8xuJEbPepXkS6jE5F+PzyoVIoWgOCsAHKsFmyRqDjwQVOgMchp8thUMillCcDnNsbTawZ78/MfKWtZd9bHAglSxjWavV6Yr6tNumiI/vyRoQNbc1nIpxwjnMd0lN5bpykTwY=
    bucket: staging.vets.gov
    skip_cleanup: true
    upload-dir: shared
    region: us-east-1
    local-dir: build
    acl: public_read
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: master
  - provider: s3
    access_key_id: AKIAJPGY3X77ZMIBM4OA
    secret_access_key:
      secure: m5rN6YkmhW8kCsd6lc7szFHmPy4iFuc8fXMLRUIGTQQCLok2xdbsx6J4CPEYbjoECTmvQ0HyBfrYDAgR9SypxBprjAs5vBUaccXxB9G9cTWinJrSRbAY2COXVXxWNfjqHZF0Jfk3UH/bzTx72BJL58vkb844RS/pEWBA/HiTmSpKTFaXwQzussMVuJdF4CROvymX0sHBurHap5Jdzytr2lV22cJ10/60rbc8S7XVACloIxsD/n/HJr79wf9J44gHbzjKEpvWpz3jsF/jTHkXkGuq/Li9qaD9mM9dCVYv7AlzXm8Wm4r8IP/qriIuOYsPouyiZHuky6y3oGDD6BaH6JAAUBwVX1e8FfxEjvDGQP4T6K0y3memwIE1NiI3JJbaqSAlNkgfHXwqE5WeP0XThK30X0B41Uu661YgGh9lTu9a2R9+XKPGjxoAi14RFNtMvS7Pwzv2jrUM7UD/7dfIQc0q3s1j/kaHkAlXi9CCvhAB9WRUXSuMJv+Zdcaua5XK0SSO8pBYT/NaY/3rI6G03I3vWG06KRZwsF0ilo2RKBtx+wH1K7tt33LBJdAx/AScoYMyY0hWCKZvtnKlvOc9Ucexy3JDC9aNOG3cvX4u5jPJLI5dpzZJE2dye5BucKkane999hmI37pgvgVE1/qdaN+NjyrGM/CX5kBs9JUfCe8=
    bucket: www.vets.gov
    skip_cleanup: true
    region: us-east-1
    local-dir: build
    acl: public_read
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: production
