language: ruby
rvm:
  - ruby-2.2

install:
  - rake install

script:
  - rake tests:ci
bundler_args: "--without development"
cache:
  - bundler
notifications:
  email: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
