language: node_js

env:
  global:
    - CXX=g++-4.8
    - AWS_ACCESS_KEY=AKIAKO2IAN6AOQEYC2HQ
    - secure: W4DamC+ysMw8/EHzlKwIh6BqLuvjQa4Nlz82SVdCPWhgaGI37Ad9k+5SmiiKWa6ZelwytYg/CMKNZKMiH7yA4HxWO297gJnllk6HmCugx6rc+WQCeBxPGRZsMsXXm5yYH0bsHtgxFi4/Mh6Vnj7n24glBjbTJU494rO0TGwtUgNXmbJ61gNtPge8u6zjFqUglewznwPQlGJ+6bEUIfP5QJg5BDljGYSadAIHzFCBkKnIYZawOFgQEv12X5nE2MB8oOtKmsAq+jYciZo9HjMre2KpPJYlcRCUsIAKcOKGVT1cKyhHBn6aj2MR/H/l2/kyXVzcehIe61gLp+fy5aCuYWlzz/1MZQs4cifHjMYtjpQ2jWDf1pGpNfjvQxM3VI/4sLIvg7Pc83QtC+T2+1OMqKXW1k1UqecDhcvyNPIVtbfmFD5rtAz5Exgv8pjLLqfdXqmHybAr+yLGXupg2UIW6Tep0G2g9HvUjK+fOYlrYIGHXopkoq8Bu3nz4Fdjgp43WQ7XciX9HD+sd0A/2jEx42PeAigN7WiaEGsORm9UQPm3WVO7AuWP5b8q1igyjNe70AQLq86K3HnVGEiofh6tdHlJGCBvhCkiKkZWDyiexLTYeSV+AaPLdwOYTgRs/A48NPWVYt1NJjdTEEfoI7uXfbtrAgdOn8jiCewmwnI6a78=

notifications:
  email: false

before_install:
  - npm install -g npm@3.8.9
  - npm --version

cache:
  apt: true
  directories:
  - node_modules

script:
  - npm run lint
  - npm run build
  - npm run selenium:bootstrap
  - npm run test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_deploy:
  - npm install -g s3-cli

deploy:
  - provider: script
    script: s3-cli sync --acl-public --delete-removed --recursive --region us-gov-west-1 build/ s3://dev.vets.gov/
    skip_cleanup: true
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: burn-the-world
  - provider: s3
    access_key_id: AKIAKO2IAN6AOQEYC2HQ # awong govcloud key.
    secret_access_key:
      secure: vsDSvLeP0CWLEAbffadOH04hriQDw/GdvuKt5me77v7SjAAzZZNb8IPai6leOebgn/Sr/NvsKXUFrMzvLUAjwmH91VDEnq/YsPWzqqlDpONTVbBkiJQDKS+plVNLQZXQ89+6WVKcAOdFLmUH5EwxUpliEGrzdCcxY6v59DiETOykhsouLwDxirBGzgfBqZ46ARiFl2xRS8HYmlavcm8SP4CQFLlFTmFVYMji3waGRk4xaXv+E50iHI2J1Hjo48C7XW/x9oITTZiZnxNLql59lzczDyvdyYBdK/nNQReBatDxUElATQ7s2CfPGDHMaRcJ+6LxxJBXo3hlhD6cDC6ao9q8SqOc1DK5aSfUkt4G97eHeKUMro+BE5+ZkJ6xAszLT19Az6CefT+pEySbLl3RYeUBRvXn+6L5kPlEcSzCX5MXuOpEvQaxAxtsD083Q5Xv6dSa0e63WxlzfqirBDqaFvOtguYnNkS/g0kYGCQBfdkdLAuR45ylE8ElBod8izmdkqGQPu2JtHuisN3VolJQS+sx8KMbwaeHRZCDPpyLjJ9EHUnnEplH+mawKqDi3zkL3PprFH5Tj3f4cVLqR62IoqTbZA8ihOLDDSjuZs9G8Txe19Ehsks0VSzgdgR12CYpW8dGa99ULxUlmYUaBZfVrxmve19vLeYtY+Xwk0+gaPg=
    bucket: dev.vets.gov
    skip_cleanup: true
    region: us-east-1
    local-dir: build
    acl: public_read
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: burn-the-worlda
  - provider: s3
    access_key_id: AKIAIEIFFI3LJZO44VTQ
    secret_access_key:
      secure: PKZPLle45zyvca1I3w8gxkwznCWM/EUqfw7W8WOGmHBDqvnZ24Cc26pOSKDE8p250rnDX42cxrnOuuGJUNpVTWoIdtKrfi3YEZi8yBXwMecKHsaZO3jQrWtGFVHV747gDmjx7THsacgAn5mvgZkuHXOZXpWcJaQtOLjLhqx++tuKSuSOkFENlRjm5fZWGUkWCBR4HjJPdfFazl8sE7TDomuOEumCjtqeKNFumlrPs+H34OyMpiMidU24Nsbla0exV7YkJTJ2PrdtkYFB3p6zZP26CHv12odkCsauZ3Ee1MUcmolNb3VgK6RPGiBvcozP7u/SdbXb5JYwBT/x/ffkowCcIZ+PNSzh/QF/TdJ0c2vtkfhTCiBDiOnBosFf3DAFCtXRCLEIlJtlxDbavBLTIEMnwkNKAQIRZP5ro4zMGjAJP/AWE0YvYZCQO8YXlb/Pl8QsH8HZY2+EYR8Qrjg/NcnnDfkg9rGdyslY/e9oMoJYYgmJlwpuIMlAWylhqUHfCzGFtUzTV+8GARjM7kkMwtIUqsjBbEYNu+kzd7O8xuJEbPepXkS6jE5F+PzyoVIoWgOCsAHKsFmyRqDjwQVOgMchp8thUMillCcDnNsbTawZ78/MfKWtZd9bHAglSxjWavV6Yr6tNumiI/vyRoQNbc1nIpxwjnMd0lN5bpykTwY=
    bucket: staging.vets.gov
    skip_cleanup: true
    upload-dir: shared
    region: us-east-1
    local-dir: build
    acl: public_read
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: master
  - provider: s3
    access_key_id: AKIAJPGY3X77ZMIBM4OA
    secret_access_key:
      secure: m5rN6YkmhW8kCsd6lc7szFHmPy4iFuc8fXMLRUIGTQQCLok2xdbsx6J4CPEYbjoECTmvQ0HyBfrYDAgR9SypxBprjAs5vBUaccXxB9G9cTWinJrSRbAY2COXVXxWNfjqHZF0Jfk3UH/bzTx72BJL58vkb844RS/pEWBA/HiTmSpKTFaXwQzussMVuJdF4CROvymX0sHBurHap5Jdzytr2lV22cJ10/60rbc8S7XVACloIxsD/n/HJr79wf9J44gHbzjKEpvWpz3jsF/jTHkXkGuq/Li9qaD9mM9dCVYv7AlzXm8Wm4r8IP/qriIuOYsPouyiZHuky6y3oGDD6BaH6JAAUBwVX1e8FfxEjvDGQP4T6K0y3memwIE1NiI3JJbaqSAlNkgfHXwqE5WeP0XThK30X0B41Uu661YgGh9lTu9a2R9+XKPGjxoAi14RFNtMvS7Pwzv2jrUM7UD/7dfIQc0q3s1j/kaHkAlXi9CCvhAB9WRUXSuMJv+Zdcaua5XK0SSO8pBYT/NaY/3rI6G03I3vWG06KRZwsF0ilo2RKBtx+wH1K7tt33LBJdAx/AScoYMyY0hWCKZvtnKlvOc9Ucexy3JDC9aNOG3cvX4u5jPJLI5dpzZJE2dye5BucKkane999hmI37pgvgVE1/qdaN+NjyrGM/CX5kBs9JUfCe8=
    bucket: www.vets.gov
    skip_cleanup: true
    region: us-east-1
    local-dir: build
    acl: public_read
    on:
      repo: department-of-veterans-affairs/vets-website
      branch: production
