name: Accessibility Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1-5'

env:
  CHROMEDRIVER_FILEPATH: /usr/local/share/chrome_driver/chromedriver
  CHANNEL_ID: C01RAS1KAQK

jobs:
  a11y:
    name: Accessibility Tests
    timeout-minutes: 120
    runs-on: [self-hosted, asg]
    strategy:
      fail-fast: false
      max-parallel: 32
      matrix:
        ci_node_total: [32]
        ci_node_index: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
    steps:
      - name: Delete Docker images
        run: |
          docker images -aq
          docker rmi -f $(docker images -aq)