name: testing

on:
  pull_request:

jobs:
  sh-runner-test:
    name: selfhosted
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: testing
        run: echo "hello"
  
  gh-runner-test:
    name: gh
    runs-on: ubuntu-latest
    needs: sh-runner-test
    steps:
      - name: testing
        run: echo "hello"
