name: Debug CI

on:
  pull_request:

jobs:
  record-metrics:
    name: Record metrics in Datadog
    runs-on: [self-hosted, linux, x64]
    env:
      METRIC_NAMESPACE: dsva_vagov.content_build_test
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/VA-Internal-S2-RCA1-v1.cer.pem
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get current timestamp
        run: echo "NOW=$(date +"%s")" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-gov-west-1

      - name: Get Datadog api key from Parameter Store
        uses: marvinpinto/action-inject-ssm-secrets@v1.2.1
        with:
          ssm_parameter: /dsva-vagov/content-build/GHA_CONTENT_BUILD_DATADOG_API_KEY
          env_variable_name: GHA_CONTENT_BUILD_DATADOG_API_KEY

      - name: Get Datadog app key from Parameter Store
        uses: marvinpinto/action-inject-ssm-secrets@v1.2.1
        with:
          ssm_parameter: /dsva-vagov/content-build/GHA_CONTENT_BUILD_DATADOG_APP_KEY
          env_variable_name: GHA_CONTENT_BUILD_DATADOG_APP_KEY

      - name: Record deployment event
        uses: ./.github/workflows/record-release-interval
        with:
          datadog_api_key: ${{ env.GHA_CONTENT_BUILD_DATADOG_API_KEY }}
          datadog_app_key: ${{ env.GHA_CONTENT_BUILD_DATADOG_APP_KEY }}
          metric_namespace: ${{ env.METRIC_NAMESPACE }}
