name: testing

on:
  pull_request:

jobs:

  set-env:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_WAIT: ${{ steps.release_wait.outputs.release_wait }}
    steps:
      - id: release_wait
        run: echo "::set-output name=release_wait::2"

  sh-runner-test:
    name: selfhosted
    needs:
      - set-env
    runs-on: [self-hosted,linux,x64]
    steps:
      - name: testing sleep
        run: |
          echo "Waiting for $(( ${{ needs.set-env.outputs.RELEASE_WAIT }} * 60 ))m"
          sleep $(( ${{ needs.set-env.outputs.RELEASE_WAIT }} * 60 ))

  gh-runner-test:
    name: gh
    runs-on: ubuntu-latest
    needs:
      - set-env
      - sh-runner-test
    steps:
      - name: testing sleep
        run: |
          echo "Waiting for $(( ${{ needs.set-env.outputs.RELEASE_WAIT }} * 60 ))m"
          sleep $(( ${{ needs.set-env.outputs.RELEASE_WAIT }} * 60 ))
